// swift-tools-version:5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FirebaseiOSSDK",
    platforms: [.iOS(.v13), .macOS(.v10_15)],
    products: [
        .library(name: "absl", targets: ["absl"]),
        .library(name: "AppAuth", targets: ["AppAuth"]),
        .library(name: "AppCheckCore", targets: ["AppCheckCore"]),
        .library(name: "FBLPromises", targets: ["FBLPromises"]),
        .library(name: "FirebaseABTesting", targets: ["FirebaseABTesting"]),
        .library(name: "FirebaseAI", targets: ["FirebaseAI"]),
        .library(name: "FirebaseAnalytics", targets: ["FirebaseAnalytics"]),
        .library(name: "FirebaseAppCheck", targets: ["FirebaseAppCheck"]),
        .library(name: "FirebaseAppCheckInterop", targets: ["FirebaseAppCheckInterop"]),
        .library(name: "FirebaseAppDistribution", targets: ["FirebaseAppDistribution"]),
        .library(name: "FirebaseAuth", targets: ["FirebaseAuth"]),
        .library(name: "FirebaseAuthInterop", targets: ["FirebaseAuthInterop"]),
        .library(name: "FirebaseCore", targets: ["FirebaseCore"]),
        .library(name: "FirebaseCoreExtension", targets: ["FirebaseCoreExtension"]),
        .library(name: "FirebaseCoreInternal", targets: ["FirebaseCoreInternal"]),
        .library(name: "FirebaseCrashlytics", targets: ["FirebaseCrashlytics"]),
        .library(name: "FirebaseDatabase", targets: ["FirebaseDatabase"]),
        .library(name: "FirebaseFirestore", targets: ["FirebaseFirestore"]),
        .library(name: "FirebaseFirestoreInternal", targets: ["FirebaseFirestoreInternal"]),
        .library(name: "FirebaseFunctions", targets: ["FirebaseFunctions"]),
        .library(name: "FirebaseInAppMessaging", targets: ["FirebaseInAppMessaging"]),
        .library(name: "FirebaseInstallations", targets: ["FirebaseInstallations"]),
        .library(name: "FirebaseMessaging", targets: ["FirebaseMessaging"]),
        .library(name: "FirebaseMessagingInterop", targets: ["FirebaseMessagingInterop"]),
        .library(name: "FirebaseMLModelDownloader", targets: ["FirebaseMLModelDownloader"]),
        .library(name: "FirebasePerformance", targets: ["FirebasePerformance"]),
        .library(name: "FirebaseRemoteConfig", targets: ["FirebaseRemoteConfig"]),
        .library(name: "FirebaseRemoteConfigInterop", targets: ["FirebaseRemoteConfigInterop"]),
        .library(name: "FirebaseSessions", targets: ["FirebaseSessions"]),
        .library(name: "FirebaseSharedSwift", targets: ["FirebaseSharedSwift"]),
        .library(name: "FirebaseStorage", targets: ["FirebaseStorage"]),
        .library(name: "GoogleAdsOnDeviceConversion", targets: ["GoogleAdsOnDeviceConversion"]),
        .library(name: "GoogleAppMeasurement", targets: ["GoogleAppMeasurement"]),
        .library(
            name: "GoogleAppMeasurementIdentitySupport",
            targets: ["GoogleAppMeasurementIdentitySupport"]
        ),
        .library(name: "GoogleDataTransport", targets: ["GoogleDataTransport"]),
        .library(name: "GoogleSignIn", targets: ["GoogleSignIn"]),
        .library(name: "GoogleUtilities", targets: ["GoogleUtilities"]),
        .library(name: "grpc", targets: ["grpc"]),
        .library(name: "grpcpp", targets: ["grpcpp"]),
        .library(name: "GTMAppAuth", targets: ["GTMAppAuth"]),
        .library(name: "GTMSessionFetcher", targets: ["GTMSessionFetcher"]),
        .library(name: "leveldb", targets: ["leveldb"]),
        .library(name: "nanopb", targets: ["nanopb"]),
        .library(name: "openssl_grpc", targets: ["openssl_grpc"]),
        .library(name: "Promises", targets: ["Promises"]),
        .library(name: "RecaptchaInterop", targets: ["RecaptchaInterop"]),
        .library(name: "SwiftProtobuf", targets: ["SwiftProtobuf"])
    ],
    targets: [
        .binaryTarget(name: "absl", path: "absl.xcframework"),
        .binaryTarget(name: "AppAuth", path: "AppAuth.xcframework"),
        .binaryTarget(name: "AppCheckCore", path: "AppCheckCore.xcframework"),
        .binaryTarget(name: "FBLPromises", path: "FBLPromises.xcframework"),
        .binaryTarget(name: "FirebaseABTesting", path: "FirebaseABTesting.xcframework"),
        .binaryTarget(name: "FirebaseAI", path: "FirebaseAI.xcframework"),
        .binaryTarget(name: "FirebaseAnalytics", path: "FirebaseAnalytics.xcframework"),
        .binaryTarget(name: "FirebaseAppCheck", path: "FirebaseAppCheck.xcframework"),
        .binaryTarget(name: "FirebaseAppCheckInterop", path: "FirebaseAppCheckInterop.xcframework"),
        .binaryTarget(name: "FirebaseAppDistribution", path: "FirebaseAppDistribution.xcframework"),
        .binaryTarget(name: "FirebaseAuth", path: "FirebaseAuth.xcframework"),
        .binaryTarget(name: "FirebaseAuthInterop", path: "FirebaseAuthInterop.xcframework"),
        .binaryTarget(name: "FirebaseCore", path: "FirebaseCore.xcframework"),
        .binaryTarget(name: "FirebaseCoreExtension", path: "FirebaseCoreExtension.xcframework"),
        .binaryTarget(name: "FirebaseCoreInternal", path: "FirebaseCoreInternal.xcframework"),
        .binaryTarget(name: "FirebaseCrashlytics", path: "FirebaseCrashlytics.xcframework"),
        .binaryTarget(name: "FirebaseDatabase", path: "FirebaseDatabase.xcframework"),
        .binaryTarget(name: "FirebaseFirestore", path: "FirebaseFirestore.xcframework"),
        .binaryTarget(name: "FirebaseFirestoreInternal", path: "FirebaseFirestoreInternal.xcframework"),
        .binaryTarget(name: "FirebaseFunctions", path: "FirebaseFunctions.xcframework"),
        .binaryTarget(name: "FirebaseInAppMessaging", path: "FirebaseInAppMessaging.xcframework"),
        .binaryTarget(name: "FirebaseInstallations", path: "FirebaseInstallations.xcframework"),
        .binaryTarget(name: "FirebaseMessaging", path: "FirebaseMessaging.xcframework"),
        .binaryTarget(name: "FirebaseMessagingInterop", path: "FirebaseMessagingInterop.xcframework"),
        .binaryTarget(name: "FirebaseMLModelDownloader", path: "FirebaseMLModelDownloader.xcframework"),
        .binaryTarget(name: "FirebasePerformance", path: "FirebasePerformance.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfig", path: "FirebaseRemoteConfig.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfigInterop", path: "FirebaseRemoteConfigInterop.xcframework"),
        .binaryTarget(name: "FirebaseSessions", path: "FirebaseSessions.xcframework"),
        .binaryTarget(name: "FirebaseSharedSwift", path: "FirebaseSharedSwift.xcframework"),
        .binaryTarget(name: "FirebaseStorage", path: "FirebaseStorage.xcframework"),
        .binaryTarget(name: "GoogleAdsOnDeviceConversion", path: "GoogleAdsOnDeviceConversion.xcframework"),
        .binaryTarget(name: "GoogleAppMeasurement", path: "GoogleAppMeasurement.xcframework"),
        .binaryTarget(
            name: "GoogleAppMeasurementIdentitySupport",
            path: "GoogleAppMeasurementIdentitySupport.xcframework"
        ),
        .binaryTarget(name: "GoogleDataTransport", path: "GoogleDataTransport.xcframework"),
        .binaryTarget(name: "GoogleSignIn", path: "GoogleSignIn.xcframework"),
        .binaryTarget(name: "GoogleUtilities", path: "GoogleUtilities.xcframework"),
        .binaryTarget(name: "grpc", path: "grpc.xcframework"),
        .binaryTarget(name: "grpcpp", path: "grpcpp.xcframework"),
        .binaryTarget(name: "GTMAppAuth", path: "GTMAppAuth.xcframework"),
        .binaryTarget(name: "GTMSessionFetcher", path: "GTMSessionFetcher.xcframework"),
        .binaryTarget(name: "leveldb", path: "leveldb.xcframework"),
        .binaryTarget(name: "nanopb", path: "nanopb.xcframework"),
        .binaryTarget(name: "openssl_grpc", path: "openssl_grpc.xcframework"),
        .binaryTarget(name: "Promises", path: "Promises.xcframework"),
        .binaryTarget(name: "RecaptchaInterop", path: "RecaptchaInterop.xcframework"),
        .binaryTarget(name: "SwiftProtobuf", path: "SwiftProtobuf.xcframework")
    ]
)
