// swift-tools-version:5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FirebaseiOSSDK",
    platforms: [.iOS(.v13), .macOS(.v10_15)],
    products: [
        .library(name: "abseil", targets: ["abseil"]),
        .library(name: "AppAuth", targets: ["AppAuth"]),
        .library(name: "BoringSSL-GRPC", targets: ["BoringSSL-GRPC"]),
        .library(name: "FBLPromises", targets: ["FBLPromises"]),
        .library(name: "FirebaseABTesting", targets: ["FirebaseABTesting"]),
        .library(name: "FirebaseAnalytics", targets: ["FirebaseAnalytics"]),
        .library(
            name: "FirebaseAnalyticsOnDeviceConversion",
            targets: ["FirebaseAnalyticsOnDeviceConversion"]
        ),
        .library(name: "FirebaseAnalyticsSwift", targets: ["FirebaseAnalyticsSwift"]),
        .library(name: "FirebaseAppCheck", targets: ["FirebaseAppCheck"]),
        .library(name: "FirebaseAppCheckInterop", targets: ["FirebaseAppCheckInterop"]),
        .library(name: "FirebaseAppDistribution", targets: ["FirebaseAppDistribution"]),
        .library(name: "FirebaseAuth", targets: ["FirebaseAuth"]),
        .library(name: "FirebaseAuthInterop", targets: ["FirebaseAuthInterop"]),
        .library(name: "FirebaseCore", targets: ["FirebaseCore"]),
        .library(name: "FirebaseCoreExtension", targets: ["FirebaseCoreExtension"]),
        .library(name: "FirebaseCoreInternal", targets: ["FirebaseCoreInternal"]),
        .library(name: "FirebaseCrashlytics", targets: ["FirebaseCrashlytics"]),
        .library(name: "FirebaseDatabase", targets: ["FirebaseDatabase"]),
        .library(name: "FirebaseDatabaseSwift", targets: ["FirebaseDatabaseSwift"]),
        .library(name: "FirebaseDynamicLinks", targets: ["FirebaseDynamicLinks"]),
        .library(name: "FirebaseFirestore", targets: ["FirebaseFirestore"]),
        .library(name: "FirebaseFirestoreSwift", targets: ["FirebaseFirestoreSwift"]),
        .library(name: "FirebaseFunctions", targets: ["FirebaseFunctions"]),
        .library(name: "FirebaseInAppMessaging", targets: ["FirebaseInAppMessaging"]),
        .library(name: "FirebaseInAppMessagingSwift", targets: ["FirebaseInAppMessagingSwift"]),
        .library(name: "FirebaseInstallations", targets: ["FirebaseInstallations"]),
        .library(name: "FirebaseMessaging", targets: ["FirebaseMessaging"]),
        .library(name: "FirebaseMessagingInterop", targets: ["FirebaseMessagingInterop"]),
        .library(name: "FirebaseMLModelDownloader", targets: ["FirebaseMLModelDownloader"]),
        .library(name: "FirebasePerformance", targets: ["FirebasePerformance"]),
        .library(name: "FirebaseRemoteConfig", targets: ["FirebaseRemoteConfig"]),
        .library(name: "FirebaseRemoteConfigSwift", targets: ["FirebaseRemoteConfigSwift"]),
        .library(name: "FirebaseSharedSwift", targets: ["FirebaseSharedSwift"]),
        .library(name: "FirebaseStorage", targets: ["FirebaseStorage"]),
        .library(name: "GoogleAppMeasurement", targets: ["GoogleAppMeasurement"]),
        .library(
            name: "GoogleAppMeasurementIdentitySupport",
            targets: ["GoogleAppMeasurementIdentitySupport"]
        ),
        .library(
            name: "GoogleAppMeasurementOnDeviceConversion",
            targets: ["GoogleAppMeasurementOnDeviceConversion"]
        ),
        .library(name: "GoogleDataTransport", targets: ["GoogleDataTransport"]),
        .library(name: "GoogleMobileAds", targets: ["GoogleMobileAds"]),
        .library(name: "GoogleSignIn", targets: ["GoogleSignIn"]),
        .library(name: "GoogleUtilities", targets: ["GoogleUtilities"]),
        .library(name: "gRPC-C++", targets: ["gRPC-C++"]),
        .library(name: "gRPC-Core", targets: ["gRPC-Core"]),
        .library(name: "GTMAppAuth", targets: ["GTMAppAuth"]),
        .library(name: "GTMSessionFetcher", targets: ["GTMSessionFetcher"]),
        .library(name: "leveldb-library", targets: ["leveldb-library"]),
        .library(name: "Libuv-gRPC", targets: ["Libuv-gRPC"]),
        .library(name: "nanopb", targets: ["nanopb"]),
        .library(name: "SwiftProtobuf", targets: ["SwiftProtobuf"]),
        .library(name: "UserMessagingPlatform", targets: ["UserMessagingPlatform"])
    ],
    targets: [
        .binaryTarget(name: "abseil", path: "abseil.xcframework"),
        .binaryTarget(name: "AppAuth", path: "AppAuth.xcframework"),
        .binaryTarget(name: "BoringSSL-GRPC", path: "BoringSSL-GRPC.xcframework"),
        .binaryTarget(name: "FBLPromises", path: "FBLPromises.xcframework"),
        .binaryTarget(name: "FirebaseABTesting", path: "FirebaseABTesting.xcframework"),
        .binaryTarget(name: "FirebaseAnalytics", path: "FirebaseAnalytics.xcframework"),
        .binaryTarget(
            name: "FirebaseAnalyticsOnDeviceConversion",
            path: "FirebaseAnalyticsOnDeviceConversion.xcframework"
        ),
        .binaryTarget(name: "FirebaseAnalyticsSwift", path: "FirebaseAnalyticsSwift.xcframework"),
        .binaryTarget(name: "FirebaseAppCheck", path: "FirebaseAppCheck.xcframework"),
        .binaryTarget(name: "FirebaseAppCheckInterop", path: "FirebaseAppCheckInterop.xcframework"),
        .binaryTarget(name: "FirebaseAppDistribution", path: "FirebaseAppDistribution.xcframework"),
        .binaryTarget(name: "FirebaseAuth", path: "FirebaseAuth.xcframework"),
        .binaryTarget(name: "FirebaseAuthInterop", path: "FirebaseAuthInterop.xcframework"),
        .binaryTarget(name: "FirebaseCore", path: "FirebaseCore.xcframework"),
        .binaryTarget(name: "FirebaseCoreExtension", path: "FirebaseCoreExtension.xcframework"),
        .binaryTarget(name: "FirebaseCoreInternal", path: "FirebaseCoreInternal.xcframework"),
        .binaryTarget(name: "FirebaseCrashlytics", path: "FirebaseCrashlytics.xcframework"),
        .binaryTarget(name: "FirebaseDatabase", path: "FirebaseDatabase.xcframework"),
        .binaryTarget(name: "FirebaseDatabaseSwift", path: "FirebaseDatabaseSwift.xcframework"),
        .binaryTarget(name: "FirebaseDynamicLinks", path: "FirebaseDynamicLinks.xcframework"),
        .binaryTarget(name: "FirebaseFirestore", path: "FirebaseFirestore.xcframework"),
        .binaryTarget(name: "FirebaseFirestoreSwift", path: "FirebaseFirestoreSwift.xcframework"),
        .binaryTarget(name: "FirebaseFunctions", path: "FirebaseFunctions.xcframework"),
        .binaryTarget(name: "FirebaseInAppMessaging", path: "FirebaseInAppMessaging.xcframework"),
        .binaryTarget(name: "FirebaseInAppMessagingSwift", path: "FirebaseInAppMessagingSwift.xcframework"),
        .binaryTarget(name: "FirebaseInstallations", path: "FirebaseInstallations.xcframework"),
        .binaryTarget(name: "FirebaseMessaging", path: "FirebaseMessaging.xcframework"),
        .binaryTarget(name: "FirebaseMessagingInterop", path: "FirebaseMessagingInterop.xcframework"),
        .binaryTarget(name: "FirebaseMLModelDownloader", path: "FirebaseMLModelDownloader.xcframework"),
        .binaryTarget(name: "FirebasePerformance", path: "FirebasePerformance.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfig", path: "FirebaseRemoteConfig.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfigSwift", path: "FirebaseRemoteConfigSwift.xcframework"),
        .binaryTarget(name: "FirebaseSharedSwift", path: "FirebaseSharedSwift.xcframework"),
        .binaryTarget(name: "FirebaseStorage", path: "FirebaseStorage.xcframework"),
        .binaryTarget(name: "GoogleAppMeasurement", path: "GoogleAppMeasurement.xcframework"),
        .binaryTarget(
            name: "GoogleAppMeasurementIdentitySupport",
            path: "GoogleAppMeasurementIdentitySupport.xcframework"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurementOnDeviceConversion",
            path: "GoogleAppMeasurementOnDeviceConversion.xcframework"
        ),
        .binaryTarget(name: "GoogleDataTransport", path: "GoogleDataTransport.xcframework"),
        .binaryTarget(name: "GoogleMobileAds", path: "GoogleMobileAds.xcframework"),
        .binaryTarget(name: "GoogleSignIn", path: "GoogleSignIn.xcframework"),
        .binaryTarget(name: "GoogleUtilities", path: "GoogleUtilities.xcframework"),
        .binaryTarget(name: "gRPC-C++", path: "gRPC-C++.xcframework"),
        .binaryTarget(name: "gRPC-Core", path: "gRPC-Core.xcframework"),
        .binaryTarget(name: "GTMAppAuth", path: "GTMAppAuth.xcframework"),
        .binaryTarget(name: "GTMSessionFetcher", path: "GTMSessionFetcher.xcframework"),
        .binaryTarget(name: "leveldb-library", path: "leveldb-library.xcframework"),
        .binaryTarget(name: "Libuv-gRPC", path: "Libuv-gRPC.xcframework"),
        .binaryTarget(name: "nanopb", path: "nanopb.xcframework"),
        .binaryTarget(name: "SwiftProtobuf", path: "SwiftProtobuf.xcframework"),
        .binaryTarget(name: "UserMessagingPlatform", path: "UserMessagingPlatform.xcframework")
    ]
)
