#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef APPCHECKCORE_SWIFT_H
#define APPCHECKCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import DeviceCheck;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AppCheckCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class GACAppCheckTokenResult;
SWIFT_PROTOCOL_NAMED("AppCheckCoreProtocol")
@protocol GACAppCheckProtocol <NSObject>
- (void)tokenForcingRefresh:(BOOL)forcingRefresh completion:(void (^ _Nonnull)(GACAppCheckTokenResult * _Nonnull))completion;
- (void)limitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckTokenResult * _Nonnull))completion;
@end

@class NSString;
@protocol GACAppCheckProvider;
@protocol GACAppCheckSettingsProtocol;
@protocol GACAppCheckTokenDelegate;
SWIFT_CLASS_NAMED("AppCheckCore")
@interface GACAppCheck : NSObject <GACAppCheckProtocol>
- (nonnull instancetype)initWithServiceName:(NSString * _Nonnull)serviceName resourceName:(NSString * _Nonnull)resourceName appCheckProvider:(id <GACAppCheckProvider> _Nonnull)appCheckProvider settings:(id <GACAppCheckSettingsProtocol> _Nonnull)settings tokenDelegate:(id <GACAppCheckTokenDelegate> _Nullable)tokenDelegate keychainAccessGroup:(NSString * _Nullable)keychainAccessGroup OBJC_DESIGNATED_INITIALIZER;
- (void)tokenForcingRefresh:(BOOL)forcingRefresh completion:(void (^ _Nonnull)(GACAppCheckTokenResult * _Nonnull))completion;
- (void)limitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckTokenResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURL;
@class NSData;
@class _GACURLSessionDataResponse;
SWIFT_CLASS_NAMED("AppCheckCoreAPIService")
@interface _GACAppCheckAPIService : NSObject
/// \param requestHooks Hooks invoked on each outgoing request. From Swift, pass
/// <code>[AppCheckCoreAPIRequestHook]</code>. From Objective-C, pass an <code>NSArray</code> of blocks with the
/// signature <code>void (^)(NSMutableURLRequest *)</code>; the signature is not checked at compile
/// time and a mismatch will crash when the hook is invoked.
/// Typed <code>[Any]?</code> rather than <code>[AppCheckCoreAPIRequestHook]?</code> deliberately: Swift cannot
/// bridge an <code>NSArray</code> into a Swift <code>Array</code> whose element is a function type, so the typed
/// signature traps at runtime for any non-nil array passed from Objective-C. Do not
/// “simplify” this type — see PR #111.
///
- (nonnull instancetype)initWithURLSession:(NSURLSession * _Nonnull)urlSession baseURL:(NSString * _Nullable)baseURL APIKey:(NSString * _Nullable)apiKey requestHooks:(NSArray * _Nullable)requestHooks;
- (void)sendRequestWithURL:(NSURL * _Nonnull)requestURL httpMethod:(NSString * _Nonnull)httpMethod body:(NSData * _Nullable)body additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nullable)additionalHeaders completionHandler:(void (^ _Nonnull)(_GACURLSessionDataResponse * _Nullable, NSError * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class GACAppCheckToken;
SWIFT_PROTOCOL_NAMED("AppCheckCoreProvider")
@protocol GACAppCheckProvider <NSObject>
- (void)getTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))completion;
- (void)getLimitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))completion;
@end

SWIFT_CLASS_NAMED("AppCheckCoreAppAttestProvider") SWIFT_AVAILABILITY(watchos,introduced=9.0) SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface GACAppAttestProvider : NSObject <GACAppCheckProvider>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
/// \param requestHooks Hooks invoked on each outgoing request. From Swift, pass
/// <code>[AppCheckCoreAPIRequestHook]</code>. From Objective-C, pass an <code>NSArray</code> of blocks with the
/// signature <code>void (^)(NSMutableURLRequest *)</code>; the signature is not checked at compile
/// time and a mismatch will crash when the hook is invoked.
/// Typed <code>[Any]?</code> rather than <code>[AppCheckCoreAPIRequestHook]?</code> deliberately: Swift cannot
/// bridge an <code>NSArray</code> into a Swift <code>Array</code> whose element is a function type, so the typed
/// signature traps at runtime for any non-nil array passed from Objective-C. Do not
/// “simplify” this type — see PR #111.
///
- (nonnull instancetype)initWithServiceName:(NSString * _Nonnull)serviceName resourceName:(NSString * _Nonnull)resourceName baseURL:(NSString * _Nullable)baseURL APIKey:(NSString * _Nullable)apiKey keychainAccessGroup:(NSString * _Nullable)accessGroup requestHooks:(NSArray * _Nullable)requestHooks;
- (void)getTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (void)getLimitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
@end

typedef SWIFT_ENUM_NAMED(NSUInteger, GACAppCheckBackoffType, "AppCheckCoreBackoffType", open) {
  GACAppCheckBackoffTypeNone = 0,
  GACAppCheckBackoffTypeOneDay = 1,
  GACAppCheckBackoffTypeExponential = 2,
};

@class NSDate;
SWIFT_CLASS_NAMED("AppCheckCoreBackoffWrapper")
@interface _GACAppCheckBackoffWrapper : NSObject
- (nonnull instancetype)init;
- (nonnull instancetype)initWithDateProvider:(NSDate * _Nonnull (^ _Nonnull)(void))dateProvider OBJC_DESIGNATED_INITIALIZER;
+ (NSDate * _Nonnull (^ _Nonnull)(void))currentDateProvider SWIFT_WARN_UNUSED_RESULT;
- (enum GACAppCheckBackoffType (^ _Nonnull)(NSError * _Nonnull))defaultAppCheckProviderErrorHandler SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("AppCheckCoreCryptoUtils")
@interface GACAppCheckCryptoUtils : NSObject
+ (NSData * _Nonnull)sha256HashFromData:(NSData * _Nonnull)dataToHash SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("AppCheckCoreDebugProvider")
@interface GACAppCheckDebugProvider : NSObject <GACAppCheckProvider>
/// \param requestHooks Hooks invoked on each outgoing request. From Swift, pass
/// <code>[AppCheckCoreAPIRequestHook]</code>. From Objective-C, pass an <code>NSArray</code> of blocks with the
/// signature <code>void (^)(NSMutableURLRequest *)</code>; the signature is not checked at compile
/// time and a mismatch will crash when the hook is invoked.
/// Typed <code>[Any]?</code> rather than <code>[AppCheckCoreAPIRequestHook]?</code> deliberately: Swift cannot
/// bridge an <code>NSArray</code> into a Swift <code>Array</code> whose element is a function type, so the typed
/// signature traps at runtime for any non-nil array passed from Objective-C. Do not
/// “simplify” this type — see PR #111.
///
- (nonnull instancetype)initWithServiceName:(NSString * _Nonnull)serviceName resourceName:(NSString * _Nonnull)resourceName baseURL:(NSString * _Nullable)baseURL APIKey:(NSString * _Nonnull)apiKey requestHooks:(NSArray * _Nullable)requestHooks;
- (NSString * _Nonnull)localDebugToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)currentDebugToken SWIFT_WARN_UNUSED_RESULT;
- (void)getTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (void)getLimitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("AppCheckCoreDeviceCheckProvider") SWIFT_AVAILABILITY(watchos,introduced=9.0) SWIFT_AVAILABILITY(tvos,introduced=11.0) SWIFT_AVAILABILITY(maccatalyst,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15) SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface GACDeviceCheckProvider : NSObject <GACAppCheckProvider>
/// \param requestHooks Hooks invoked on each outgoing request. From Swift, pass
/// <code>[AppCheckCoreAPIRequestHook]</code>. From Objective-C, pass an <code>NSArray</code> of blocks with the
/// signature <code>void (^)(NSMutableURLRequest *)</code>; the signature is not checked at compile
/// time and a mismatch will crash when the hook is invoked.
/// Typed <code>[Any]?</code> rather than <code>[AppCheckCoreAPIRequestHook]?</code> deliberately: Swift cannot
/// bridge an <code>NSArray</code> into a Swift <code>Array</code> whose element is a function type, so the typed
/// signature traps at runtime for any non-nil array passed from Objective-C. Do not
/// “simplify” this type — see PR #111.
///
- (nonnull instancetype)initWithServiceName:(NSString * _Nonnull)serviceName resourceName:(NSString * _Nonnull)resourceName APIKey:(NSString * _Nonnull)apiKey requestHooks:(NSArray * _Nullable)requestHooks OBJC_DESIGNATED_INITIALIZER;
- (void)getTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (void)getLimitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("AppCheckCoreDeviceCheckTokenGenerator")
@protocol GACDeviceCheckTokenGenerator <NSObject>
@property (nonatomic, readonly) BOOL isSupported;
- (void)generateTokenWithCompletionHandler:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completionHandler;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, GACAppCheckErrorCode, "AppCheckCoreErrorCode", open) {
/// An unknown or non-actionable error.
  GACAppCheckErrorCodeUnknown = 0,
/// A network connection error.
  GACAppCheckErrorCodeServerUnreachable = 1,
/// Invalid configuration error. Currently, an exception is thrown but this error is reserved
/// for future implementations of invalid configuration detection.
  GACAppCheckErrorCodeInvalidConfiguration = 2,
/// System keychain access error. Ensure that the app has proper keychain access.
  GACAppCheckErrorCodeKeychain = 3,
/// Selected app attestation provider is not supported on the current platform or OS version.
  GACAppCheckErrorCodeUnsupported = 4,
};
static NSString * _Nonnull const GACAppCheckErrorCodeDomain = @"AppCheckCore.AppCheckCoreErrorCode";

@class NSHTTPURLResponse;
@class GACAppCheckHTTPError;
@class NSError;
SWIFT_CLASS_NAMED("AppCheckCoreErrorUtil")
@interface _GACAppCheckErrorUtil : NSObject
+ (NSError * _Nonnull)publicDomainErrorWith:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)cachedTokenNotFound SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)cachedTokenExpired SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)keychainErrorWith:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
+ (GACAppCheckHTTPError * _Nonnull)apiErrorWith:(NSHTTPURLResponse * _Nonnull)httpResponse data:(NSData * _Nullable)data SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)apiErrorWithNetworkError:(NSError * _Nonnull)networkError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appCheckTokenResponseErrorWithMissingField:(NSString * _Nonnull)fieldName SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appAttestAttestationResponseErrorWithMissingField:(NSString * _Nonnull)fieldName SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)jsonSerializationError:(NSError * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)errorWithFailureReason:(NSString * _Nonnull)failureReason SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)unsupportedAttestationProvider:(NSString * _Nonnull)providerName SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)missingRecaptchaSDKError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appAttestKeyIDNotFound SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appAttestGenerateKeyFailedWith:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appAttestAttestKeyFailedWith:(NSError * _Nonnull)error keyId:(NSString * _Nonnull)keyId clientDataHash:(NSData * _Nonnull)clientDataHash SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appAttestGenerateAssertionFailedWith:(NSError * _Nonnull)error keyId:(NSString * _Nonnull)keyId clientDataHash:(NSData * _Nonnull)clientDataHash SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)unknownErrorWith:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)appCheckErrorWithCode:(enum GACAppCheckErrorCode)code failureReason:(NSString * _Nullable)failureReason underlyingError:(NSError * _Nullable)underlyingError SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)errorDescriptionWithDeviceCheckError:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Objective-C accessor for the App Check error domain.
/// Swift global constants are not bridged to Objective-C, so the v11
/// <code>GACAppCheckErrorDomain</code> global is no longer visible there. Objective-C
/// callers should use <code>GACAppCheckErrors.errorDomain</code> instead:
/// \code
/// if ([error.domain isEqualToString:GACAppCheckErrors.errorDomain]) { ... }
///
/// \endcode
SWIFT_CLASS_NAMED("AppCheckCoreErrorsObjC")
@interface GACAppCheckErrors : NSObject
/// The App Check error domain. Equivalent to the Swift
/// <code>AppCheckCoreErrorDomain</code> global.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull errorDomain;)
+ (NSString * _Nonnull)errorDomain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
SWIFT_CLASS_NAMED("AppCheckCoreHTTPError")
@interface GACAppCheckHTTPError : NSError
@property (nonatomic, readonly, strong) NSHTTPURLResponse * _Nonnull httpResponse;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithHTTPResponse:(NSHTTPURLResponse * _Nonnull)httpResponse data:(NSData * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, GACAppCheckLogLevel, "AppCheckCoreLogLevel", open) {
  GACAppCheckLogLevelDebug = 1,
  GACAppCheckLogLevelInfo = 2,
  GACAppCheckLogLevelWarning = 3,
  GACAppCheckLogLevelError = 4,
  GACAppCheckLogLevelFault = 5,
};

SWIFT_CLASS_NAMED("AppCheckCoreLogger")
@interface GACAppCheckLogger : NSObject
/// The current log level.
/// Access is serialized by a lock to match the <code>atomic</code> semantics of the
/// Objective-C <code>GACAppCheckLogger.logLevel</code> class property, which was backed
/// by a <code>volatile</code> static.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum GACAppCheckLogLevel logLevel;)
+ (enum GACAppCheckLogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogLevel:(enum GACAppCheckLogLevel)newValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, GACAppCheckMessageCode, "AppCheckCoreMessageCode", open) {
  GACAppCheckMessageCodeUnknown = 1001,
  GACAppCheckMessageCodeProviderIsMissing = 2002,
  GACAppCheckMessageCodeStagingModeEnabled = 2003,
  GACAppCheckMessageCodeUnexpectedHTTPCode = 3001,
  GACAppCheckMessageCodeInvalidRequestHook = 3002,
  GACAppCheckMessageCodeLocalDebugToken = 4001,
  GACAppCheckMessageCodeEnvironmentVariableDebugToken = 4002,
  GACAppCheckMessageCodeDebugProviderFirebaseEnvironmentVariable = 4003,
  GACAppCheckMessageCodeDebugProviderFailedExchange = 4004,
  GACAppCheckMessageCodeAppAttestNotSupported = 7001,
  GACAppCheckMessageCodeAttestationRejected = 7002,
  GACAppCheckMessageCodeAssertionRejected = 7003,
};

SWIFT_PROTOCOL_NAMED("AppCheckCoreSettingsProtocol")
@protocol GACAppCheckSettingsProtocol <NSObject>
@property (nonatomic) BOOL isTokenAutoRefreshEnabled;
@end

SWIFT_CLASS_NAMED("AppCheckCoreSettings")
@interface GACAppCheckSettings : NSObject <GACAppCheckSettingsProtocol>
@property (nonatomic) BOOL isTokenAutoRefreshEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("AppCheckCoreToken")
@interface GACAppCheckToken : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
@property (nonatomic, readonly, copy) NSDate * _Nonnull expirationDate;
@property (nonatomic, readonly, copy) NSDate * _Nonnull receivedAtDate;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token expirationDate:(NSDate * _Nonnull)expirationDate receivedAtDate:(NSDate * _Nonnull)receivedAtDate OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token expirationDate:(NSDate * _Nonnull)expirationDate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("AppCheckCoreTokenDelegate")
@protocol GACAppCheckTokenDelegate <NSObject>
- (void)tokenDidUpdate:(GACAppCheckToken * _Nonnull)token serviceName:(NSString * _Nonnull)serviceName;
@end

SWIFT_CLASS_NAMED("AppCheckCoreTokenResult")
@interface GACAppCheckTokenResult : NSObject
@property (nonatomic, readonly, strong) GACAppCheckToken * _Nonnull token;
@property (nonatomic, readonly) NSError * _Nullable error;
- (nonnull instancetype)initWithToken:(GACAppCheckToken * _Nonnull)token error:(NSError * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithToken:(GACAppCheckToken * _Nonnull)token;
- (nonnull instancetype)initWithError:(NSError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The class represents HTTP response received from <code>URLSession</code>.
SWIFT_CLASS_NAMED("AppCheckCoreURLSessionDataResponse")
@interface _GACURLSessionDataResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Firebase App Check provider that verifies app integrity using the
/// <a href="https://firebase.google.com/docs/app-check/ios/recaptcha-enterprise-provider">reCAPTCHA
/// Enterprise</a>
/// API. This class’s platform and OS availability matches reCAPTCHA
/// Enterprise’s.
SWIFT_CLASS_NAMED("AppCheckRecaptchaProvider") SWIFT_AVAILABILITY(watchos,unavailable) SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(maccatalyst,unavailable) SWIFT_AVAILABILITY(macos,unavailable) SWIFT_AVAILABILITY(visionos,introduced=1.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface GACRecaptchaProvider : NSObject <GACAppCheckProvider>
+ (BOOL)isSupported SWIFT_WARN_UNUSED_RESULT;
/// The default initializer.
/// \param siteKey The reCAPTCHA site key.
///
/// \param resourceName The name of the resource protected by App Check; for a Firebase App this is
/// “projects/{project_id}/apps/{app_id}”.
///
/// \param APIKey The Google Cloud Platform API key.
///
/// \param requestHooks Hooks invoked on each outgoing request. From Swift, pass
/// <code>[AppCheckCoreAPIRequestHook]</code>. From Objective-C, pass an <code>NSArray</code> of blocks with the
/// signature <code>void (^)(NSMutableURLRequest *)</code>; the signature is not checked at compile
/// time and a mismatch will crash when the hook is invoked.
/// Typed <code>[Any]?</code> rather than <code>[AppCheckCoreAPIRequestHook]?</code> deliberately: Swift cannot
/// bridge an <code>NSArray</code> into a Swift <code>Array</code> whose element is a function type, so the typed
/// signature traps at runtime for any non-nil array passed from Objective-C. Do not
/// “simplify” this type — see PR #111.
///
- (nullable instancetype)initWithSiteKey:(NSString * _Nonnull)siteKey resourceName:(NSString * _Nonnull)resourceName APIKey:(NSString * _Nonnull)APIKey requestHooks:(NSArray * _Nullable)requestHooks;
/// \param siteKey The reCAPTCHA site key.
///
/// \param resourceName The name of the resource protected by App Check; for a Firebase App this is
/// “projects/{project_id}/apps/{app_id}”.
///
/// \param APIKey The Google Cloud Platform API key.
///
/// \param requestHooks Hooks invoked on each outgoing request. From Swift, pass
/// <code>[AppCheckCoreAPIRequestHook]</code>. From Objective-C, pass an <code>NSArray</code> of blocks with the
/// signature <code>void (^)(NSMutableURLRequest *)</code>; the signature is not checked at compile
/// time and a mismatch will crash when the hook is invoked.
/// Typed <code>[Any]?</code> rather than <code>[AppCheckCoreAPIRequestHook]?</code> deliberately: Swift cannot
/// bridge an <code>NSArray</code> into a Swift <code>Array</code> whose element is a function type, so the typed
/// signature traps at runtime for any non-nil array passed from Objective-C. Do not
/// “simplify” this type — see PR #111.
///
/// \param actionName The reCAPTCHA custom action name.
///
- (nullable instancetype)initWithSiteKey:(NSString * _Nonnull)siteKey resourceName:(NSString * _Nonnull)resourceName APIKey:(NSString * _Nonnull)APIKey requestHooks:(NSArray * _Nullable)requestHooks actionName:(NSString * _Nonnull)actionName;
- (void)getTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (void)getLimitedUseTokenWithCompletion:(void (^ _Nonnull)(GACAppCheckToken * _Nullable, NSError * _Nullable))handler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_AVAILABILITY(watchos,introduced=9.0) SWIFT_AVAILABILITY(tvos,introduced=11.0) SWIFT_AVAILABILITY(macos,introduced=10.15) SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface DCDevice (SWIFT_EXTENSION(AppCheckCore)) <GACDeviceCheckTokenGenerator>
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
